jobs:
- job: MacOS_CI_Dev
  pool:
    vmImage: 'macOS-10.13'
  steps:
    - script: |
        sudo xcode-select --switch /Applications/Xcode_10.app/Contents/Developer
        ./build.sh --skip_submodule_sync --parallel --build_shared_lib
      displayName: 'Command Line Script'

    - template: templates/clean-agent-build-directory-step.yml